export const repositories = [
  {
    name: 'design-system',
    visibility: 'Public',
    language: 'React',
    size: 7320,
    lastUpdate: '1 day ago',
  },
  {
    name: 'codeant-ci-app',
    visibility: 'Private',
    language: 'Javascript',
    size: 5871,
    lastUpdate: '2 days ago',
  },
  {
    name: 'analytics-dashboard',
    visibility: 'Private',
    language: 'Python',
    size: 4521,
    lastUpdate: '5 days ago',
  },
  {
    name: 'mobile-app',
    visibility: 'Public',
    language: 'Swift',
    size: 3096,
    lastUpdate: '3 days ago',
  },
  {
    name: 'e-commerce-platform',
    visibility: 'Private',
    language: 'Java',
    size: 6210,
    lastUpdate: '6 days ago',
  },
  {
    name: 'blog-website',
    visibility: 'Public',
    language: 'HTML/CSS',
    size: 1876,
    lastUpdate: '4 days ago',
  },
  {
    name: 'social-network',
    visibility: 'Private',
    language: 'PHP',
    size: 5432,
    lastUpdate: '7 days ago',
  },
  {
    name: 'portfolio-site',
    visibility: 'Public',
    language: 'HTML/CSS',
    size: 2450,
    lastUpdate: '2 days ago',
  },
  {
    name: 'chatbot-service',
    visibility: 'Private',
    language: 'Python',
    size: 6780,
    lastUpdate: '3 days ago',
  },
  {
    name: 'task-manager',
    visibility: 'Public',
    language: 'React',
    size: 4823,
    lastUpdate: '1 day ago',
  },
  {
    name: 'payment-gateway',
    visibility: 'Private',
    language: 'Java',
    size: 7145,
    lastUpdate: '5 days ago',
  },
  {
    name: 'weather-app',
    visibility: 'Public',
    language: 'Javascript',
    size: 3421,
    lastUpdate: '4 days ago',
  },
  {
    name: 'forum-platform',
    visibility: 'Private',
    language: 'PHP',
    size: 5912,
    lastUpdate: '6 days ago',
  },
];
